"""empty message

Revision ID: 0cd974a3833f
Revises: bee4994c9b79
Create Date: 2017-06-22 12:34:58.744662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd974a3833f'
down_revision = 'bee4994c9b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('current_pool_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carpooler', 'pool', ['current_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carpooler', type_='foreignkey')
    op.drop_column('carpooler', 'current_pool_id')
    # ### end Alembic commands ###
