"""empty message

Revision ID: 10580a61cfd8
Revises: f888792c50bb
Create Date: 2017-05-20 04:11:06.881809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10580a61cfd8'
down_revision = 'f888792c50bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('menu', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'menu')
    # ### end Alembic commands ###
