"""empty message

Revision ID: 1bddc085b826
Revises: bdd41b13e489
Create Date: 2017-07-03 18:40:34.150776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bddc085b826'
down_revision = 'bdd41b13e489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poolName', sa.String(), nullable=True),
    sa.Column('eventDate', sa.String(), nullable=True),
    sa.Column('eventTime', sa.String(), nullable=True),
    sa.Column('eventDateTime', sa.DateTime(), nullable=True),
    sa.Column('latenessWindow', sa.Integer(), nullable=True),
    sa.Column('eventAddress', sa.String(), nullable=True),
    sa.Column('eventContact', sa.String(), nullable=True),
    sa.Column('eventEmail', sa.String(), nullable=True),
    sa.Column('eventHostOrg', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('fireNotice', sa.String(), nullable=True),
    sa.Column('selfRep', sa.Text(), nullable=True),
    sa.Column('selfFormalRep', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carpooler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_pool_id', sa.Integer(), nullable=True),
    sa.Column('fbId', sa.String(), nullable=True),
    sa.Column('selfRep', sa.Text(), nullable=True),
    sa.Column('selfFormalRep', sa.Text(), nullable=True),
    sa.Column('fieldstate', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('carpooler_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('preWindow', sa.Integer(), nullable=True),
    sa.Column('on_time', sa.Integer(), nullable=True),
    sa.Column('must_drive', sa.Integer(), nullable=True),
    sa.Column('selfRep', sa.Text(), nullable=True),
    sa.Column('selfFormalRep', sa.Text(), nullable=True),
    sa.Column('poolRepLoaded', sa.Integer(), nullable=True),
    sa.Column('carpoolerRepLoaded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('carpooler_id', 'pool_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('carpooler')
    op.drop_table('pool')
    # ### end Alembic commands ###
