"""empty message

Revision ID: 2632481d9007
Revises: e37a3715ed20
Create Date: 2017-05-16 02:41:13.243578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2632481d9007'
down_revision = 'e37a3715ed20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpooler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fbId', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('preWindow', sa.Integer(), nullable=True),
    sa.Column('need_to_arrive_on_time', sa.Integer(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('engaged', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poolName', sa.String(), nullable=True),
    sa.Column('eventDate', sa.Date(), nullable=True),
    sa.Column('eventTime', sa.Time(), nullable=True),
    sa.Column('eventAddress', sa.String(), nullable=True),
    sa.Column('eventContact', sa.String(), nullable=True),
    sa.Column('eventEmail', sa.String(), nullable=True),
    sa.Column('eventHostOrg', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('carpooler_id', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('pool')
    op.drop_table('carpooler')
    # ### end Alembic commands ###
