"""empty message

Revision ID: 26f02e2d18d3
Revises: 2bbb8df30e5b
Create Date: 2017-06-20 13:59:06.620305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f02e2d18d3'
down_revision = '2bbb8df30e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('selfFormalRep', sa.Text(), nullable=True))
    op.add_column('trips', sa.Column('selfRep', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'selfRep')
    op.drop_column('trips', 'selfFormalRep')
    # ### end Alembic commands ###
