"""empty message

Revision ID: 2bbb8df30e5b
Revises: dd216dadf114
Create Date: 2017-06-18 12:30:31.135483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbb8df30e5b'
down_revision = 'dd216dadf114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'must_drive')
    op.drop_column('carpooler', 'num_seats')
    op.drop_column('carpooler', 'preWindow')
    op.drop_column('carpooler', 'address')
    op.drop_column('carpooler', 'on_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('on_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carpooler', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carpooler', sa.Column('preWindow', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carpooler', sa.Column('num_seats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carpooler', sa.Column('must_drive', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
