"""empty message

Revision ID: 3ce459d23bd2
Revises: c87dc06d7b5c
Create Date: 2017-08-30 01:15:25.829173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce459d23bd2'
down_revision = 'c87dc06d7b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempTeams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('carpooler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempTeams')
    # ### end Alembic commands ###
