"""empty message

Revision ID: 3d3780ed3c00
Revises: 10580a61cfd8
Create Date: 2017-05-20 07:27:54.267771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3780ed3c00'
down_revision = '10580a61cfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('confirming', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'confirming')
    # ### end Alembic commands ###
