"""empty message

Revision ID: 559f680f5372
Revises: aff0bf1590cd
Create Date: 2017-08-30 14:57:49.860006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '559f680f5372'
down_revision = 'aff0bf1590cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carpooler', '_password',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('pool', 'eventDateTime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pool', 'eventDateTime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('carpooler', '_password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
