"""empty message

Revision ID: 6957bd2d3230
Revises: 
Create Date: 2017-05-22 15:43:44.605742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6957bd2d3230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpooler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fbId', sa.String(), nullable=True),
    sa.Column('engaged', sa.Integer(), nullable=True),
    sa.Column('fieldstate', sa.String(), nullable=True),
    sa.Column('selfRep', sa.Text(), nullable=True),
    sa.Column('selfFormalRep', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('preWindow', sa.Integer(), nullable=True),
    sa.Column('on_time', sa.Integer(), nullable=True),
    sa.Column('must_drive', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('confirming', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poolName', sa.String(), nullable=True),
    sa.Column('eventDate', sa.Date(), nullable=True),
    sa.Column('eventTime', sa.Time(), nullable=True),
    sa.Column('latenessWindow', sa.Integer(), nullable=True),
    sa.Column('eventAddress', sa.String(), nullable=True),
    sa.Column('eventContact', sa.String(), nullable=True),
    sa.Column('eventEmail', sa.String(), nullable=True),
    sa.Column('eventHostOrg', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('carpooler_id', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('pool')
    op.drop_table('carpooler')
    # ### end Alembic commands ###
