"""empty message

Revision ID: 80db1fd4ee9d
Revises: ce9a4b25f12d
Create Date: 2017-07-03 18:54:44.705592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80db1fd4ee9d'
down_revision = 'ce9a4b25f12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('eventDateTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'eventDateTime')
    # ### end Alembic commands ###
