"""empty message

Revision ID: 937df0385487
Revises: b6c70853e2f0
Create Date: 2017-08-22 14:51:52.578397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937df0385487'
down_revision = 'b6c70853e2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'password')
    # ### end Alembic commands ###
