"""empty message

Revision ID: 9e48e0ed5ece
Revises: f7dd156b01a7
Create Date: 2017-06-05 14:35:02.049371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e48e0ed5ece'
down_revision = 'f7dd156b01a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'confirming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('confirming', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
