"""empty message

Revision ID: aff0bf1590cd
Revises: 0fbea90e9183
Create Date: 2017-08-30 14:39:38.439128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff0bf1590cd'
down_revision = '0fbea90e9183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'temp_teams', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_teams', type_='unique')
    # ### end Alembic commands ###
