"""empty message

Revision ID: b6c70853e2f0
Revises: da5e714ca710
Create Date: 2017-08-21 13:40:20.618140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c70853e2f0'
down_revision = 'da5e714ca710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('email', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'email')
    # ### end Alembic commands ###
