"""empty message

Revision ID: bdd41b13e489
Revises: 0cd974a3833f
Create Date: 2017-06-28 00:06:19.786360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd41b13e489'
down_revision = '0cd974a3833f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('eventDateTime', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'eventDateTime')
    # ### end Alembic commands ###
