"""empty message

Revision ID: c10f02bc354b
Revises: 9e503f012309
Create Date: 2017-05-22 07:07:04.919341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10f02bc354b'
down_revision = '9e503f012309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('selfFormalRep', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'selfFormalRep')
    # ### end Alembic commands ###
