"""empty message

Revision ID: c87dc06d7b5c
Revises: 78f91627511b
Create Date: 2017-08-29 13:34:00.399792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87dc06d7b5c'
down_revision = '78f91627511b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('_password', sa.String(), nullable=True))
    op.drop_column('carpooler', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carpooler', '_password')
    # ### end Alembic commands ###
