"""empty message

Revision ID: d00b2dfdd556
Revises: 559f680f5372
Create Date: 2017-08-30 22:30:05.763253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00b2dfdd556'
down_revision = '559f680f5372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_event_dists',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('carpooler_id', sa.Integer(), nullable=False),
    sa.Column('feet', sa.Integer(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'carpooler_id')
    )
    op.create_table('trip_dists',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('from_carpooler_id', sa.Integer(), nullable=False),
    sa.Column('to_carpooler_id', sa.Integer(), nullable=False),
    sa.Column('feet', sa.Integer(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.ForeignKeyConstraint(['to_carpooler_id'], ['carpooler.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'from_carpooler_id', 'to_carpooler_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_dists')
    op.drop_table('to_event_dists')
    # ### end Alembic commands ###
