"""empty message

Revision ID: d293aa38645a
Revises: e3a6f0210814
Create Date: 2017-08-07 10:49:00.506868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd293aa38645a'
down_revision = 'e3a6f0210814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pool', sa.Column('optimizationCurrent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pool', 'optimizationCurrent')
    # ### end Alembic commands ###
