"""empty message

Revision ID: da5e714ca710
Revises: 
Create Date: 2017-08-21 13:19:06.699430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5e714ca710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_membership')
    op.drop_table('team_affiliation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_affiliation',
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], name='team_affiliation_pool_id_fkey'),
    sa.PrimaryKeyConstraint('pool_id', name='team_affiliation_pkey')
    )
    op.create_table('team_membership',
    sa.Column('carpooler_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], name='team_membership_carpooler_id_fkey'),
    sa.PrimaryKeyConstraint('carpooler_id', name='team_membership_pkey')
    )
    # ### end Alembic commands ###
