"""empty message

Revision ID: dd216dadf114
Revises: 9e48e0ed5ece
Create Date: 2017-06-18 10:56:20.361504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd216dadf114'
down_revision = '9e48e0ed5ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('carpooler_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('preWindow', sa.Integer(), nullable=True),
    sa.Column('on_time', sa.Integer(), nullable=True),
    sa.Column('must_drive', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ),
    sa.PrimaryKeyConstraint('carpooler_id', 'pool_id')
    )
    op.drop_table('participation')
    op.drop_column('carpooler', 'engaged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('engaged', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('participation',
    sa.Column('carpooler_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pool_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['carpooler_id'], ['carpooler.id'], name='participation_carpooler_id_fkey'),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], name='participation_pool_id_fkey')
    )
    op.drop_table('trips')
    # ### end Alembic commands ###
