"""empty message

Revision ID: f7dd156b01a7
Revises: 6957bd2d3230
Create Date: 2017-06-05 14:31:02.092356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7dd156b01a7'
down_revision = '6957bd2d3230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpooler', sa.Column('mode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpooler', 'mode')
    # ### end Alembic commands ###
